codecov:
  require_ci_to_pass: false
comment:
  behavior: default
  layout: "reach, diff, flags, files"
coverage:
  precision: 2
  range:
  - 50.0
  - 100.0
  round: down
  status:
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error
    changes:
      default:
        target: auto
        threshold: 0%
        base: auto
github_checks:
  annotations: true

